---
title: Rosalvo Melo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    featured_video: 
    thumbnail_image: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: 
github_username: 
markdown: kramdown
plugins:
- jekyll-feed
layouts_dir: "./_layouts"
data_dir: "./_data"
include:
- _pages
