---
title: Rosalvo Melo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    featured_video: 
    thumbnail_image: 
email: 
description: 
baseurl: 
url: 
sass:
  style: compressed
markdown: kramdown
layouts_dir: "./_layouts"
data_dir: "./_data"
permalink: pretty
include:
- _pages
socials:
- name: Instagram
  url: http://instagram.com/rosalvomelo
  position: 5
  icon: ''
- name: Vimeo
  url: http://vimeo.com/rosalvomelo
  position: 2
  icon: ''
- name: LinkedIn
  url: http://uk.linkedin.com/in/rosalvomelo
  position: 3
  icon: ''
- name: Facebook
  url: http://facebook.com/rosalvomeloo
  position: 4
  icon: ''
