---
title: Rosalvo Melo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    featured_video: 
    thumbnail_image: 
email: 
description: 
baseurl: 
url: 
sass:
  style: compressed
markdown: kramdown
layouts_dir: "./_layouts"
data_dir: "./_data"
permalink: pretty
include:
- _pages
